# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    command: [--auth]
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      APP_MONGO_DB: ${APP_MONGO_DB}
      APP_MONGO_USERNAME: ${APP_MONGO_USERNAME}
      APP_MONGO_PASSWORD: ${APP_MONGO_PASSWORD}
    volumes:
      - ./data/:/data/db
      - ./mongo-scripts/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_FRONT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_FRONT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
